### ISSUE TITLE
Strange behavior when precompiling assets

### ISSUE THREAD

**Issue by tscolari** [jimsynz/hamlbars#21]
I'm having a very strange error when I try to precompile assets using hamlbars.
If I rename the templates to jst.eco, everything runs fine:

```
$bundle exec rake RAILS_ENV=staging RAILS_GROUPS=assets assets:precompile --trace
** Invoke assets:precompile (first_time)
** Execute assets:precompile
** Invoke assets:precompile:all (first_time)
** Execute assets:precompile:all
** Invoke assets:precompile:primary (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Execute assets:precompile:primary
** Invoke assets:precompile:nondigest (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Execute assets:precompile:nondigest
```

But, if I move them back to .js.hamlbars, this is what I get:

```
$bundle exec rake RAILS_ENV=staging RAILS_GROUPS=assets assets:precompile --trace
** Invoke assets:precompile (first_time)
** Execute assets:precompile
** Invoke assets:precompile:all (first_time)
** Execute assets:precompile:all
** Invoke assets:precompile:primary (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Execute assets:precompile:primary
rake aborted!
File to import not found or unreadable: clearfix.
Load path: Sass::Rails::Importer(/.../app/assets/stylesheets/layout.scss)
  (in /.../app/assets/stylesheets/layout.scss)
/.../app/assets/stylesheets/mixins/_mixins.scss:1
/.../app/assets/stylesheets/layout.scss:2
/.../.rvm/gems/ruby-1.9.3-p125@tudogostoso/gems/sass-3.1.16/lib/sass/tree/import_node.rb:64:in `rescue in import'
/.../.rvm/gems/ruby-1.9.3-p125@tudogostoso/gems/sass-3.1.16/lib/sass/tree/import_node.rb:42:in `import'
/.../.rvm/gems/ruby-1.9.3-p125@tudogostoso/gems/sass-3.1.16/lib/sass/tree/import_node.rb:25:in `imported_file'
/.../.rvm/gems/ruby-1.9.3-p125@tudogostoso/gems/sass-3.1.16/lib/sass/tree/visitors/perform.rb:149:in `rescue in visit_import'
/.../.rvm/gems/ruby-1.9.3-p125@tudogostoso/gems/sass-3.1.16/lib/sass/tree/visitors/perform.rb:154:in `visit_import'
/.../.rvm/gems/ruby-1.9.3-p125@tudogostoso/gems/sass-3.1.16/lib/sass/tree/visitors/base.rb:37:in `visit'
/.../.rvm/gems/ruby-1.9.3-p125@tudogostoso/gems/sass-3.1.16/lib/sass/tree/visitors/perform.rb:18:in `visit'
/.../.rvm/gems/ruby-1.9.3-p125@tudogostoso/gems/sass-3.1.16/lib/sass/tree/visitors/perform.rb:146:in `block in visit_import'
...
```

It seems that, when I use it, sass get lost loading it's includes. This only happens if I request the templates on my js manifest, and only when compiling assets. In development mode I get no error at all.

Am I the only one having this issue?

**Comment by tscolari** [comment]
I think something is messing the load paths. I'm trying to trace the error here, it seems that after compiling hamlbars, for some reason, sass/sprockets stop loading subfolders with sass patials.

for example, given the structure:

```
- app
  - assets
    - stylesheets
      layout.css.scc ( @include 'mixins' )
      - mixins
        _mixins.scss ( @include 'clearfix' )
        _clearfix.scss
```

Sass get lost on the `include clearfix`, but using `@include 'mixins/clearfix'` works.
Im looking on some sass issues to see of there is anything there.

**Comment by jimsynz** [comment]
That's pretty weird (and also not happening for me), but I haven't used any sass partials.  Can you try and come up with a minimal example that I can take a look at?

**Comment by jimsynz** [comment]
@tscolari any updates or should I close this issue?

**Comment by tscolari** [comment]
I don't have news on this.
We had our templates changed for coffeescript for other reasons.
