### ISSUE TITLE
Hamlbars fails with Haml 3.2

### ISSUE THREAD

**Issue by inkstak** [jimsynz/hamlbars#27]
Hi,

I tried to use hamlbars, with the latest version of haml :

```
gem 'haml', '>= 3.2.0.beta' 
gem 'hamlbars'
```

.. and got the following error, when launching rails :

```
[...]/gems/hamlbars-1.0.0/lib/hamlbars/ext/compiler.rb:9:in `<module:Haml>': Compiler is not a module (TypeError)
    from [...]/gems/hamlbars-1.0.0/lib/hamlbars/ext/compiler.rb:8:in `<top (required)>'
    from [...]/gems/hamlbars-1.0.0/lib/hamlbars.rb:16:in `<module:Hamlbars>'
    from [...]/gems/hamlbars-1.0.0/lib/hamlbars.rb:4:in `<top (required)>'
```

It works fine with haml 3.1.x.

**Comment by jimsynz** [comment]
Thanks for the report. I'll start looking into it.

**Comment by jimsynz** [comment]
This has been fixed with #30. Can you verify your app with Hamlbars 1.1?

**Comment by inkstak** [comment]
It works fine. Thanks !

**Comment by jimsynz** [comment]
Yay!
